# Generated by Django 3.2.13 on 2022-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(default=' ', max_length=150, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30, null=True, verbose_name='昵称'),
        ),
    ]
