dict_data = {
    "subjects":[
        {
            "episodes_info":"",
            "rate":"7.3",
            "cover_x":3158,
            "title":"小黄人大眼萌：神偷奶爸前传",
            "url":"https:\/\/movie.douban.com\/subject\/26642033\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2870674906.jpg",
            "id":"26642033",
            "cover_y":5000,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"7.5",
            "cover_x":1200,
            "title":"犯罪都市2",
            "url":"https:\/\/movie.douban.com\/subject\/30267287\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2872991814.jpg",
            "id":"30267287",
            "cover_y":1716,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.5",
            "cover_x":1080,
            "title":"雪山飞狐之塞北宝藏",
            "url":"https:\/\/movie.douban.com\/subject\/35357255\/",
            "playable":'true',
            "cover":"https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2876020592.jpg",
            "id":"35357255",
            "cover_y":1512,
            "is_new":'true'
        },
        {
            "episodes_info":"",
            "rate":"6.8",
            "cover_x":1000,
            "title":"女孩画像",
            "url":"https:\/\/movie.douban.com\/subject\/35305649\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2772248698.jpg",
            "id":"35305649",
            "cover_y":1410,
            "is_new":'true'
        },
        {
            "episodes_info":"",
            "rate":"6.9",
            "cover_x":1000,
            "title":"春天",
            "url":"https:\/\/movie.douban.com\/subject\/35382350\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2634388287.jpg",
            "id":"35382350",
            "cover_y":1545,
            "is_new":'true'
        },
        {
            "episodes_info":"",
            "rate":"6.6",
            "cover_x":1500,
            "title":"灰影人",
            "url":"https:\/\/movie.douban.com\/subject\/7051806\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2873535079.jpg",
            "id":"7051806",
            "cover_y":2222,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.8",
            "cover_x":4050,
            "title":"光年正传",
            "url":"https:\/\/movie.douban.com\/subject\/35284168\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2873213286.jpg",
            "id":"35284168",
            "cover_y":6000,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.1",
            "cover_x":2000,
            "title":"魔女2",
            "url":"https:\/\/movie.douban.com\/subject\/34832354\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2872429677.jpg",
            "id":"34832354",
            "cover_y":2860,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.9",
            "cover_x":1920,
            "title":"咒",
            "url":"https:\/\/movie.douban.com\/subject\/34850561\/",
            "playable":'false',
            "cover":"https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2871258860.jpg",
            "id":"34850561",
            "cover_y":2782,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"8.6",
            "cover_x":1403,
            "title":"宿敌",
            "url":"https:\/\/movie.douban.com\/subject\/35882880\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2874026114.jpg",
            "id":"35882880",
            "cover_y":2048,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.7",
            "cover_x":1400,
            "title":"掮客",
            "url":"https:\/\/movie.douban.com\/subject\/35192111\/",
            "playable":'false',
            "cover":"https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2876193091.jpg",
            "id":"35192111",
            "cover_y":1998,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.8",
            "cover_x":1294,
            "title":"黑色电话",
            "url":"https:\/\/movie.douban.com\/subject\/35238569\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2687007137.jpg",
            "id":"35238569",
            "cover_y":2048,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"5.6",
            "cover_x":1080,
            "title":"恶到必除",
            "url":"https:\/\/movie.douban.com\/subject\/36017416\/",
            "playable":'true',
            "cover":"https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2876793472.jpg",
            "id":"36017416",
            "cover_y":1920,
            "is_new":'true'
        },
        {
            "episodes_info":"",
            "rate":"8.2",
            "cover_x":1170,
            "title":"祝你好运，里奥·格兰德",
            "url":"https:\/\/movie.douban.com\/subject\/35235813\/",
            "playable":'false',
            "cover":"https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2872943472.jpg",
            "id":"35235813",
            "cover_y":1721,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.1",
            "cover_x":3500,
            "title":"侏罗纪世界3",
            "url":"https:\/\/movie.douban.com\/subject\/26873582\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2873135507.jpg",
            "id":"26873582",
            "cover_y":5187,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"6.3",
            "cover_x":1711,
            "title":"奇异博士2：疯狂多元宇宙",
            "url":"https:\/\/movie.douban.com\/subject\/30304994\/",
            "playable":'false',
            "cover":"https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2872533452.jpg",
            "id":"30304994",
            "cover_y":2500,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"8.1",
            "cover_x":2000,
            "title":"天鹅挽歌",
            "url":"https:\/\/movie.douban.com\/subject\/35258381\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2717809625.jpg",
            "id":"35258381",
            "cover_y":3000,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"7.6",
            "cover_x":1000,
            "title":"唯爱永存",
            "url":"https:\/\/movie.douban.com\/subject\/35891625\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2874508798.jpg",
            "id":"35891625",
            "cover_y":1481,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"7.4",
            "cover_x":2835,
            "title":"谁是超级英雄",
            "url":"https:\/\/movie.douban.com\/subject\/35212079\/",
            "playable":'false',
            "cover":"https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2708256204.jpg",
            "id":"35212079",
            "cover_y":3850,
            "is_new":'false'
        },
        {
            "episodes_info":"",
            "rate":"8.0",
            "cover_x":1371,
            "title":"巴黎夜旅人",
            "url":"https:\/\/movie.douban.com\/subject\/35354759\/",
            "playable":'false',
            "cover":"https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2871210079.jpg",
            "id":"35354759",
            "cover_y":1866,
            "is_new":'false'
        }
    ]
}

print(dict_data, type(dict_data))

# 要求：将20部电影的标题（title）/评分（rete）/电影的地址（url）/封面图片地址（cover）
#  将地址处理为正确的格式：