# Generated by Django 3.2.13 on 2022-11-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作家')),
            ],
            options={
                'db_table': 'oto_author',
            },
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='妻子')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.author')),
            ],
            options={
                'db_table': 'oto_wife',
            },
        ),
    ]
