# Generated by Django 3.2.13 on 2022-11-12 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('category', models.CharField(max_length=20, verbose_name='内容分类')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('introduce', models.CharField(default='进来看看吧', max_length=128, verbose_name='内容简介')),
                ('limit', models.CharField(max_length=20, verbose_name='查看权限')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击量')),
                ('recommend', models.FloatField(default=0.0, verbose_name='推荐值')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
